import { useEffect,useState } from 'react';import { base44 } from '@/api/base44Client';import { loadCreatorProfile } from '@/lib/creatorProfile';
const defaults={portfolio_theme:'editorial',background_style:'light',accent_color:'#111111',typography_style:'editorial',layout_style:'asymmetric',portfolio_intro:'',portfolio_prompt:'',hero_image:'',portfolio_section_order:['hero','work','about','services','contact'],hidden_sections:[]};
const configFrom=profile=>({...defaults,...Object.fromEntries(Object.keys(defaults).filter(key=>profile[key]!==undefined).map(key=>[key,profile[key]]))});
const chooseTheme=text=>{const value=text.toLowerCase();if(/playful|colorful/.test(value))return ['playful','grid','expressive'];if(/bold|experimental|raw/.test(value))return ['bold','asymmetric','modern'];if(/minimal|clean|monochrome/.test(value))return ['minimal','grid','modern'];return ['editorial','asymmetric','editorial']};
export default function usePortfolioBuilder(){const [profile,setProfile]=useState(null);const [assets,setAssets]=useState([]);const [config,setConfig]=useState(defaults);const [stage,setStage]=useState('upload');const [loading,setLoading]=useState(true);const [uploading,setUploading]=useState(false);const [generating,setGenerating]=useState(false);const [error,setError]=useState('');
useEffect(()=>{loadCreatorProfile().then(async({profile})=>{setProfile(profile);if(profile){const rows=await base44.entities.PortfolioAsset.filter({profile_id:profile.id},'sort_order');setAssets(rows);setConfig(configFrom(profile));if(profile.portfolio_theme&&rows.length)setStage('studio')}setLoading(false)})},[]);
const uploadFiles=async files=>{const accepted=[...files].filter(file=>file.type.startsWith('image/')||file.type.startsWith('video/'));if(!accepted.length)return;setUploading(true);setError('');try{const uploads=await Promise.all(accepted.map(file=>base44.integrations.Core.UploadFile({file}).then(({file_url})=>({profile_id:profile.id,file_url,file_name:file.name,media_type:file.type.startsWith('video/')?'video':'image',selected:true,sort_order:assets.length,visibility:'draft'}))));const created=await base44.entities.PortfolioAsset.bulkCreate(uploads.map((item,index)=>({...item,sort_order:assets.length+index})));setAssets(current=>[...current,...created])}catch(e){setError(e.message||'Upload failed. Please try again.')}finally{setUploading(false)}};
const changeAsset=async(id,change)=>{setAssets(current=>current.map(item=>item.id===id?{...item,...change}:item));await base44.entities.PortfolioAsset.update(id,change)};
const removeAsset=async id=>{await base44.entities.PortfolioAsset.delete(id);setAssets(current=>current.filter(item=>item.id!==id))};
const moveAsset=async(index,direction)=>{const target=index+direction;if(target<0||target>=assets.length)return;const next=[...assets];[next[index],next[target]]=[next[target],next[index]];const ordered=next.map((item,i)=>({...item,sort_order:i}));setAssets(ordered);await base44.entities.PortfolioAsset.bulkUpdate(ordered.map(({id,sort_order})=>({id,sort_order})))};
const generate=async(prompt,chips)=>{setGenerating(true);setError('');try{const [theme,layout,type]=chooseTheme(`${prompt} ${chips.join(' ')}`);const hero=assets.find(item=>item.selected&&item.media_type==='image')?.file_url||assets.find(item=>item.selected)?.file_url||'';const next={...config,portfolio_theme:theme,layout_style:layout,typography_style:type,portfolio_prompt:prompt,portfolio_intro:profile.short_bio,hero_image:hero};setConfig(next);await base44.entities.CreativeProfile.update(profile.id,{...next,portfolio_status:'draft'});setStage('studio')}catch(e){setError(e.message||'Portfolio generation failed.')}finally{setGenerating(false)}};
const save=async publish=>{const change={...config,portfolio_status:publish?'published':'draft',marketplace_eligible:publish,...(publish?{published_date:new Date().toISOString()}:{})};await base44.entities.CreativeProfile.update(profile.id,change);if(assets.length)await base44.entities.PortfolioAsset.bulkUpdate(assets.map(item=>({id:item.id,visibility:publish?'published':'draft'})));setProfile(current=>({...current,...change}));return change};
const importUrl=async url=>{await base44.entities.CreativeProfile.update(profile.id,{existing_portfolio_url:url});setProfile(current=>({...current,existing_portfolio_url:url}))};
return{profile,assets,config,setConfig,stage,setStage,loading,uploading,generating,error,uploadFiles,changeAsset,removeAsset,moveAsset,generate,save,importUrl}}