import { Link, useNavigate } from 'react-router-dom';import { ArrowRight, Search } from 'lucide-react';import { useState } from 'react';import PageShell from '@/components/PageShell';import CreativeCard from '@/components/CreativeCard';import ProjectCard from '@/components/ProjectCard';import EventCard from '@/components/EventCard';import { creatives,projects,events } from '@/data/marketplace';
function Home() { const [q,setQ]=useState('');const nav=useNavigate();const [saved,setSaved]=useState(()=>JSON.parse(localStorage.getItem('savedCreatives')||'[]'));const toggle=id=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);localStorage.setItem('savedCreatives',JSON.stringify(next))};return <PageShell>
<section className="grid min-h-[72vh] lg:grid-cols-2"><div className="flex flex-col justify-center px-6 py-20 lg:px-14 xl:px-24"><p className="mb-6 text-xs uppercase tracking-[.22em]">New York City · Creative Marketplace</p><h1 className="max-w-2xl text-6xl font-semibold leading-[.92] tracking-[-.06em] sm:text-7xl xl:text-8xl">Find the people who make ideas happen.</h1><p className="mt-7 max-w-lg text-lg leading-relaxed text-black/60">Discover photographers, stylists, filmmakers, designers, and creative talent through the work they make.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/marketplace" className="rounded-full bg-black px-6 py-3 text-white">Find creative talent</Link><Link to="/profile" className="rounded-full border border-black px-6 py-3">Join as a creative</Link></div></div><div className="min-h-[520px] bg-[url('https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1600&q=90')] bg-cover bg-center" /></section>
<section className="border-y border-black/10 px-5 py-10 lg:px-10"><form onSubmit={e=>{e.preventDefault();nav(`/marketplace?q=${encodeURIComponent(q)}`)}} className="mx-auto flex max-w-5xl items-center gap-4 border-b-2 border-black pb-4"><Search/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full bg-transparent text-xl outline-none sm:text-3xl" placeholder="What kind of creative are you looking for?"/><button className="hidden rounded-full bg-black px-5 py-2 text-sm text-white sm:block">Search</button></form></section>
<section className="mx-auto max-w-[1500px] px-5 py-20 lg:px-10"><div className="mb-9 flex items-end justify-between"><div><p className="section-kicker">Discover</p><h2 className="section-title">Featured creatives</h2></div><Link to="/marketplace" className="flex items-center gap-2 text-sm">View all <ArrowRight className="h-4 w-4"/></Link></div><div className="grid grid-cols-1 gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{creatives.slice(0,3).map(c=><CreativeCard key={c.id} creative={c} saved={saved.includes(c.id)} onSave={toggle}/>)}</div></section>
<section className="mx-auto max-w-[1500px] px-5 pb-20 lg:px-10"><div className="mb-9 flex items-end justify-between"><div><p className="section-kicker">Available Now</p><h2 className="section-title">Available This Weekend</h2></div><Link to="/marketplace" className="flex items-center gap-2 text-sm">Explore Marketplace <ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-x-5 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{creatives.filter(c=>c.availability.toLowerCase().includes('weekend')).map(c=><CreativeCard key={c.id} creative={c} saved={saved.includes(c.id)} onSave={toggle}/>)}</div></section>
<section className="bg-[#dedbd2] px-5 py-20 lg:px-10"><div className="mx-auto max-w-[1500px]"><p className="section-kicker">Relevant Projects</p><h2 className="section-title mb-9">Creative Work in NYC</h2><div className="grid gap-6 md:grid-cols-3">{projects.map(p=><ProjectCard key={p.id} project={p}/>)}</div></div></section>
<section className="mx-auto max-w-[1500px] px-5 py-20 lg:px-10"><p className="section-kicker">Community</p><h2 className="section-title mb-9">Upcoming Community Events</h2><div className="grid gap-6 md:grid-cols-3">{events.map(e=><EventCard key={e.id} event={e}/>)}</div></section>
<section className="border-t border-black/10 px-5 py-24 text-center"><h2 className="text-5xl font-semibold tracking-[-.05em] sm:text-7xl">Make something together.</h2><Link to="/marketplace" className="mt-8 inline-flex items-center gap-2 rounded-full bg-black px-6 py-3 text-white">Start discovering <ArrowRight className="h-4 w-4"/></Link></section></PageShell>}

export default Home;