import { Camera,Scissors,Paintbrush,ArrowDown,ArrowRight,ArrowUpLeft } from 'lucide-react';
const steps=[
 {title:'YOU CREATE',copy:'Capture your vision',Icon:Camera,tone:'bg-story-rose',position:'left-0 top-2'},
 {title:'YOU COLLABORATE',copy:'Bring the right people in',Icon:Scissors,tone:'bg-story-gold',position:'right-0 top-2'},
 {title:'YOU CREATE TOGETHER',copy:'Elevate the work',Icon:Paintbrush,tone:'bg-story-olive text-primary-foreground',position:'bottom-2 right-0'}
];
function StoryCard({step}){const {title,copy,Icon,tone}=step;return <article className="flex items-center gap-3"><div className={`flex h-16 w-16 shrink-0 items-center justify-center rounded-[62%_38%_54%_46%/44%_57%_43%_56%] ${tone}`}><Icon className="h-7 w-7" strokeWidth={1.35}/></div><div><p className="text-[10px] font-semibold tracking-[.16em]">{title}</p><p className="mt-1 text-sm leading-tight text-black/55">{copy}</p></div></article>}
function Artwork(){return <article className="border border-black/20 bg-home p-3 shadow-[0_12px_30px_rgba(43,38,32,.08)]"><div className="relative aspect-[4/3] overflow-hidden bg-story-dust"><span className="absolute -left-5 top-4 h-24 w-24 rounded-full bg-story-aubergine"/><span className="absolute bottom-3 right-3 h-16 w-24 rotate-[-12deg] bg-story-rose"/><span className="absolute right-7 top-5 h-20 w-3 rotate-[28deg] bg-story-gold"/></div><p className="mt-3 text-[10px] font-semibold tracking-[.16em]">YOUR WORK GETS SEEN</p><p className="mt-1 text-sm text-black/55">In the right places</p></article>}
function Opportunity(){return <article className="rotate-[-2deg] border border-black/20 bg-home p-4 shadow-[0_10px_24px_rgba(43,38,32,.07)]"><p className="text-[9px] font-semibold tracking-[.18em] text-terracotta">NEW OPPORTUNITY</p><p className="mt-2 font-semibold">Brand Campaign</p><p className="text-sm text-black/50">Creative Direction</p><div className="mt-4 border-t border-black/15 pt-3"><p className="text-[10px] font-semibold tracking-[.14em]">THE NEXT OPPORTUNITY</p><p className="mt-1 text-sm text-black/55">Leads to what’s next</p></div></article>}
export default function CareerLoopIllustration(){return <div><div className="space-y-5 sm:hidden">{steps.map((step,index)=><div key={step.title}><StoryCard step={step}/>{index<steps.length-1&&<ArrowDown className="ml-7 mt-4 h-4 w-4 text-black/30"/>}</div>)}<ArrowDown className="ml-7 h-4 w-4 text-black/30"/><Artwork/><ArrowDown className="ml-7 h-4 w-4 text-black/30"/><Opportunity/><div className="flex items-center gap-2 text-xs uppercase tracking-[.14em] text-black/45"><ArrowUpLeft className="h-4 w-4"/>Back to making</div></div><div className="relative hidden aspect-square sm:block"><div className="absolute inset-[8%] rounded-[48%_52%_47%_53%/55%_44%_56%_45%] border border-dashed border-black/20"/>{steps.map(step=><div key={step.title} className={`absolute z-10 w-[42%] bg-home p-3 ${step.position}`}><StoryCard step={step}/></div>)}<div className="absolute left-[29%] top-[34%] z-10 w-[42%]"><Artwork/></div><div className="absolute bottom-1 left-0 z-10 w-[40%]"><Opportunity/></div><ArrowRight className="absolute left-[48%] top-[8%] h-5 w-5 text-black/35"/><ArrowDown className="absolute right-[8%] top-[46%] h-5 w-5 text-black/35"/><ArrowUpLeft className="absolute bottom-[18%] left-[8%] h-5 w-5 text-black/35"/></div></div>}